version: '3.7'

services:
  traefik:
    image: traefik:v2.0.2
    container_name: traefik
    command:
      - --log.level=ERROR
      - --ping=true
      - --accesslog=true
      - --accesslog.format=json
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.network=traefik
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http
      - --entrypoints.http.address=:80
      - --entrypoints.https
      - --entrypoints.https.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=info@zczoft.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    dns:
      - 8.8.8.8
      - 9.9.9.9
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=PathPrefix(`/ping`) || Host(`traefik.{{ domain_name }}`)
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik.entrypoints=http
volumes:
    traefik_data:

networks:
    traefik:
        external: true
